#!/bin/bash
echo "╔════════════════════════════════════════════════════════════╗"
echo "║        SamvaadAIoT Status Check                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 BRANDING FILES:"
echo "  NOTICE: $([ -f NOTICE ] && echo '✓ EXISTS' || echo '✗ MISSING')"
echo "  README.md: $([ -f README.md ] && echo '✓ EXISTS' || echo '✗ MISSING')"
echo "  package.json: $(grep -q 'samvaadaiot' ui-ngx/package.json && echo '✓ UPDATED' || echo '✗ NOT UPDATED')"
echo "  Favicon: $([ -f ui-ngx/src/samvaad.ico ] && echo '✓ EXISTS' || echo '✗ MISSING')"
echo "  Logo: $([ -f ui-ngx/src/assets/logo/samvaad-logo.png ] && echo '✓ EXISTS' || echo '✗ MISSING')"
echo "  Theme: $([ -f ui-ngx/src/samvaad-custom.scss ] && echo '✓ EXISTS' || echo '✗ MISSING')"
echo ""
echo "🏗️  BUILD STATUS:"
ps aux | grep -q "[n]pm start" && echo "  Dev Server: ✓ RUNNING" || echo "  Dev Server: ✗ NOT RUNNING"
netstat -tuln 2>/dev/null | grep -q ":4200" && echo "  Port 4200: ✓ LISTENING" || echo "  Port 4200: - CHECKING..."
echo ""
echo "📊 FILE COUNT:"
echo "  Modified files: $(git status --short 2>/dev/null | wc -l) changes"
echo ""
echo "═══════════════════════════════════════════════════════════"
